#!/usr/bin/env bats
# Unit tests for pr_build_description footer append behavior.
# Covers: missing footer, empty footer, present footer, trailing newlines,
# WORKSPACE_ROOT vs cwd resolution.

load '../helpers/test_helper'

PR_MANAGER_LIB="${BATS_TEST_DIRNAME}/../../lib/pr_manager.sh"

setup() {
    TEST_DIR="$(mktemp -d)"
    cd "$TEST_DIR"
    mkdir -p .ralph
    echo "PASS: echo ok" > .ralph/.quality_gate_results

    source "$PR_MANAGER_LIB"

    log_status() { :; }
    export -f log_status

    export RALPH_ENGINE="test-engine"
    unset WORKSPACE_ROOT
}

teardown() {
    unset WORKSPACE_ROOT
    if [[ -n "$TEST_DIR" && -d "$TEST_DIR" ]]; then
        cd /
        rm -rf "$TEST_DIR"
    fi
}

# --- helpers ---------------------------------------------------------------

_call_build_desc() {
    pr_build_description "T-1" "sample task" "feat/x" "true" \
        "$TEST_DIR/.ralph/.quality_gate_results" "7"
}

# =============================================================================
# Missing footer → body unchanged (regression guard)
# =============================================================================

@test "pr_build_description: no footer file → no footer appended" {
    [[ ! -e ".ralph/pr_footer.md" ]]
    run _call_build_desc
    assert_success

    # Last non-empty line must be the generated ralph signature, not footer text.
    [[ "$output" == *"Generated by Ralph"* ]]
    last_line=$(printf '%s\n' "$output" | tail -n1)
    [[ "$last_line" == *"Generated by Ralph"* ]]
}

# =============================================================================
# Empty footer → body unchanged
# =============================================================================

@test "pr_build_description: empty footer file → no footer appended" {
    : > .ralph/pr_footer.md
    [[ -f ".ralph/pr_footer.md" ]]
    [[ ! -s ".ralph/pr_footer.md" ]]

    run _call_build_desc
    assert_success

    last_line=$(printf '%s\n' "$output" | tail -n1)
    [[ "$last_line" == *"Generated by Ralph"* ]]
}

# =============================================================================
# Present footer with content → appended to end of body
# =============================================================================

@test "pr_build_description: footer with content → appended verbatim" {
    cat > .ralph/pr_footer.md <<'EOF'
## Steering drift

- deploy-flag: false
- owner: platform-team
EOF

    run _call_build_desc
    assert_success

    [[ "$output" == *"## Steering drift"* ]]
    [[ "$output" == *"deploy-flag: false"* ]]
    [[ "$output" == *"owner: platform-team"* ]]

    # Footer must come AFTER the ralph signature line.
    sig_line=$(printf '%s\n' "$output" | grep -n "Generated by Ralph" | head -n1 | cut -d: -f1)
    footer_line=$(printf '%s\n' "$output" | grep -n "## Steering drift" | head -n1 | cut -d: -f1)
    [[ -n "$sig_line" ]]
    [[ -n "$footer_line" ]]
    (( footer_line > sig_line ))
}

@test "pr_build_description: body ends with footer's last content line" {
    cat > .ralph/pr_footer.md <<'EOF'
footer-first
footer-last
EOF

    run _call_build_desc
    assert_success

    last_line=$(printf '%s\n' "$output" | tail -n1)
    [[ "$last_line" == "footer-last" ]]
}

# =============================================================================
# Footer with trailing newlines → content preserved
# =============================================================================

@test "pr_build_description: footer with trailing newlines → all lines preserved" {
    printf 'line-a\nline-b\n\n\n' > .ralph/pr_footer.md

    run _call_build_desc
    assert_success

    [[ "$output" == *"line-a"* ]]
    [[ "$output" == *"line-b"* ]]

    # Both lines must appear after the ralph signature.
    sig_line=$(printf '%s\n' "$output" | grep -n "Generated by Ralph" | head -n1 | cut -d: -f1)
    a_line=$(printf '%s\n' "$output" | grep -n "line-a" | head -n1 | cut -d: -f1)
    b_line=$(printf '%s\n' "$output" | grep -n "line-b" | head -n1 | cut -d: -f1)
    (( a_line > sig_line ))
    (( b_line > a_line ))
}

# =============================================================================
# Resolver: WORKSPACE_ROOT set vs unset
# =============================================================================

@test "pr_build_description: WORKSPACE_ROOT set → resolves footer under WORKSPACE_ROOT" {
    mkdir -p ws-root/.ralph
    echo "workspace-footer-mark" > ws-root/.ralph/pr_footer.md

    # cwd has a DIFFERENT footer to confirm resolver prefers WORKSPACE_ROOT.
    echo "cwd-footer-mark" > .ralph/pr_footer.md

    export WORKSPACE_ROOT="$TEST_DIR/ws-root"
    run _call_build_desc
    assert_success

    [[ "$output" == *"workspace-footer-mark"* ]]
    [[ "$output" != *"cwd-footer-mark"* ]]
}

@test "pr_build_description: WORKSPACE_ROOT unset → resolves footer under cwd" {
    echo "cwd-footer-mark" > .ralph/pr_footer.md

    unset WORKSPACE_ROOT
    run _call_build_desc
    assert_success

    [[ "$output" == *"cwd-footer-mark"* ]]
}

@test "pr_build_description: WORKSPACE_ROOT set but footer missing there → no footer, even if cwd footer exists" {
    mkdir -p ws-root/.ralph
    # No footer file under ws-root.

    echo "cwd-footer-mark" > .ralph/pr_footer.md

    export WORKSPACE_ROOT="$TEST_DIR/ws-root"
    run _call_build_desc
    assert_success

    [[ "$output" != *"cwd-footer-mark"* ]]
    last_line=$(printf '%s\n' "$output" | tail -n1)
    [[ "$last_line" == *"Generated by Ralph"* ]]
}

# =============================================================================
# Separator: footer separated from ralph signature by blank line
# =============================================================================

@test "pr_build_description: blank line between ralph signature and footer" {
    echo "FOOTER_CONTENT" > .ralph/pr_footer.md

    run _call_build_desc
    assert_success

    # Expect pattern: <ralph line>\n\nFOOTER_CONTENT in output.
    [[ "$output" == *$'\n\nFOOTER_CONTENT'* ]]
}
